SistemaGestorRecursosHumanos/Controllers/cargosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaGestorRecursosHumanos.Models;

namespace SistemaGestorRecursosHumanos.Controllers
{
    public class cargosController : Controller
    {
        private SGRHEntities db = new SGRHEntities();

        // GET: cargos
        public ActionResult Index()
        {
            return View(db.cargos.ToList());
        }

        // GET: cargos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cargos cargos = db.cargos.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // GET: cargos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: cargos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_cargos,codigoCargo,cargo")] cargos cargos)
        {
            if (ModelState.IsValid)
            {
                db.cargos.Add(cargos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cargos);
        }

        // GET: cargos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cargos cargos = db.cargos.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // POST: cargos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_cargos,codigoCargo,cargo")] cargos cargos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cargos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cargos);
        }

        // GET: cargos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            cargos cargos = db.cargos.Find(id);
            if (cargos == null)
            {
                return HttpNotFound();
            }
            return View(cargos);
        }

        // POST: cargos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            cargos cargos = db.cargos.Find(id);
            db.cargos.Remove(cargos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaGestorRecursosHumanos/Controllers/empleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaGestorRecursosHumanos.Models;

namespace SistemaGestorRecursosHumanos.Controllers
{
    public class empleadosController : Controller
    {
        private SGRHEntities db = new SGRHEntities();

        // GET: empleados
        public ActionResult Index()
        {
            var empleados = db.empleados.Include(e => e.cargos).Include(e => e.departamentos);
            return View(empleados.ToList());
        }

        // GET: empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            empleados empleados = db.empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // GET: empleados/Create
        public ActionResult Create()
        {
            ViewBag.id_cargos = new SelectList(db.cargos, "id_cargos", "codigoCargo");
            ViewBag.id_departamento = new SelectList(db.departamentos, "id_departamento", "codigoDepartamento");
            return View();
        }

        // POST: empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,codigoEmpleado,nombre,apellido,telefono,fechaIngreso,salario,estado,id_departamento,id_cargos")] empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.empleados.Add(empleados);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_cargos = new SelectList(db.cargos, "id_cargos", "codigoCargo", empleados.id_cargos);
            ViewBag.id_departamento = new SelectList(db.departamentos, "id_departamento", "codigoDepartamento", empleados.id_departamento);
            return View(empleados);
        }

        // GET: empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            empleados empleados = db.empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_cargos = new SelectList(db.cargos, "id_cargos", "codigoCargo", empleados.id_cargos);
            ViewBag.id_departamento = new SelectList(db.departamentos, "id_departamento", "codigoDepartamento", empleados.id_departamento);
            return View(empleados);
        }

        // POST: empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,codigoEmpleado,nombre,apellido,telefono,fechaIngreso,salario,estado,id_departamento,id_cargos")] empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleados).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_cargos = new SelectList(db.cargos, "id_cargos", "codigoCargo", empleados.id_cargos);
            ViewBag.id_departamento = new SelectList(db.departamentos, "id_departamento", "codigoDepartamento", empleados.id_departamento);
            return View(empleados);
        }

        // GET: empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            empleados empleados = db.empleados.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // POST: empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            empleados empleados = db.empleados.Find(id);
            db.empleados.Remove(empleados);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaGestorRecursosHumanos/Controllers/nominasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaGestorRecursosHumanos.Models;

namespace SistemaGestorRecursosHumanos.Controllers
{
    public class nominasController : Controller
    {
        private SGRHEntities db = new SGRHEntities();

        // GET: nominas
        public ActionResult Index()
        {
            return View(db.nomina.ToList());
        }

        // GET: nominas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nomina nomina = db.nomina.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        // GET: nominas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: nominas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_nomina,año,mes,montoTotal")] nomina nomina)
        {
            if (ModelState.IsValid)
            {
                db.nomina.Add(nomina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nomina);
        }

        // GET: nominas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nomina nomina = db.nomina.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        // POST: nominas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_nomina,año,mes,montoTotal")] nomina nomina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nomina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nomina);
        }

        // GET: nominas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            nomina nomina = db.nomina.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        // POST: nominas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            nomina nomina = db.nomina.Find(id);
            db.nomina.Remove(nomina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaGestorRecursosHumanos/Controllers/permisosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SistemaGestorRecursosHumanos.Models;

namespace SistemaGestorRecursosHumanos.Controllers
{
    public class permisosController : Controller
    {
        private SGRHEntities db = new SGRHEntities();

        // GET: permisos
        public ActionResult Index()
        {
            var permisos = db.permisos.Include(p => p.empleados);
            return View(permisos.ToList());
        }

        //mostrar Permisos
        public ActionResult Permisosx()        {            return View(db.permisos.ToListAsync());        }        [HttpPost]        [ValidateAntiForgeryToken]        public ActionResult Permisosx(string fecha)        {
                IEnumerable<permisos> permisos;

            

                using (var bd = new SGRHEntities())
                {
                permisos = bd.permisos;

                    if (!String.IsNullOrEmpty(fecha))
                    {
                    DateTime fechax = DateTime.Parse(fecha);

                    permisos = permisos.Where(x => x.desde.Equals(fechax));
                    }

                    permisos = permisos.ToList();
                }

                return View(permisos);         }

        // GET: permisos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permisos permisos = db.permisos.Find(id);
            if (permisos == null)
            {
                return HttpNotFound();
            }
            return View(permisos);
        }

        // GET: permisos/Create
        public ActionResult Create()
        {
            ViewBag.id_empleado = new SelectList(db.empleados, "id", "codigoEmpleado");
            return View();
        }

        // POST: permisos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_permiso,desde,hasta,comentario,id_empleado")] permisos permisos)
        {
            if (ModelState.IsValid)
            {
                db.permisos.Add(permisos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_empleado = new SelectList(db.empleados, "id", "codigoEmpleado", permisos.id_empleado);
            return View(permisos);
        }

        // GET: permisos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permisos permisos = db.permisos.Find(id);
            if (permisos == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_empleado = new SelectList(db.empleados, "id", "codigoEmpleado", permisos.id_empleado);
            return View(permisos);
        }

        // POST: permisos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_permiso,desde,hasta,comentario,id_empleado")] permisos permisos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(permisos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_empleado = new SelectList(db.empleados, "id", "codigoEmpleado", permisos.id_empleado);
            return View(permisos);
        }

        // GET: permisos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            permisos permisos = db.permisos.Find(id);
            if (permisos == null)
            {
                return HttpNotFound();
            }
            return View(permisos);
        }

        // POST: permisos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            permisos permisos = db.permisos.Find(id);
            db.permisos.Remove(permisos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SistemaGestorRecursosHumanos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SistemaGestorRecursosHumanos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SistemaGestorRecursosHumanos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="container">

    <h2>Bienvenido a este sistema</h2>

    <p class="text-primary">Este es un sistema que permite gestionar los recursos humanos de una empresa, <br />asi como tambien busca bridar las herramientas necesarias
    para que nuestros <br /> clientes queden satisfechos con los servicios que aqui le brindamos.</p>

    <p class="text-primary">Debajo se encuentran dos botones que lo enviaran a los modulos principales de este sistema,<br /> dentro de ellos encontrara los contenidos correspondiente
    de cada uno</p>
    <div class="row">
        <div class="col-md-4">
            @Html.ActionLink("Modulo de Mantenimiento", "mantenimiento", "Home", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-4">
            @Html.ActionLink("Modulo de Procesos", "procesos", "Home", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-4">
            @Html.ActionLink("Informes", "informes", "Home", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

SistemaGestorRecursosHumanos/Views/Home/informes.cshtml
@{
    ViewBag.Title = "informes";
}

<h2>informes</h2>

<div class="container">
    <div class="row">
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de nomina", "index", "nominas", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de empleados", "index", "empleados", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de departamentos", "index", "departamentos", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de cargos", "index", "cargos", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de Entrada de empleados", "index", "entradaEmpleados", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de salida de empleados", "index", "salidaEmpleados", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de Vacaciones ", "index", "vacaciones", null, new { @class = "btn btn-primary btn-large" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Informe de permisos", "index", "permisos", null, new { @class = "btn btn-primary btn-large" })
        </div>
    </div>
</div>

SistemaGestorRecursosHumanos/Views/Home/mantenimiento.cshtml
@{
    ViewBag.Title = "mantenimiento";
}


<div class="container">

    <h2>Modulo de mantenimiento</h2>
    <div class="row">
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver Empleados", "index", "empleados", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Agregar Empleado", "create", "empleados", null, new { @class = "btn btn-primary" })
        </div>

        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver Departamentos", "index", "departamentos", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Agregar Departamento", "create", "departamentos", null, new { @class = "btn btn-primary" })
        </div>

        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver Cargos", "index", "cargos", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Agregar Cargo", "create", "cargos", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

SistemaGestorRecursosHumanos/Views/Home/procesos.cshtml
@{
    ViewBag.Title = "procesos";
}

<h2>procesos</h2>

<div class="container">

    <h2>Modulo procesos</h2>
    <div class="row">
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver calculo nomina", "index", "nominas", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Dar salida a empleado", "create", "salidaEmpleadoes", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Dar permisos", "create", "permisos", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver permisos", "index", "permisos", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Dar vacaciones", "create", "vacaciones", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver vacaciones", "index", "vacaciones", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Dar licencia", "create", "licencias", null, new { @class = "btn btn-primary" })
        </div>
        <div class="col-md-5" style="margin-bottom: 20px">
            @Html.ActionLink("Ver licencias", "index", "licencias", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>